name: Fuzzing CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  Fuzz:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Initialize image name
      run: ./name.sh
    - name: Build and run the Docker image
      run: ./build.sh
    - name: Run fuzz job
      run: |
        docker --version
        docker images
        ./run.sh
        
