name: Fuzzing CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Initialize image name
      run: ./name.sh
    - name: Build the Docker image
      run: build.sh
    - name: Run the docker image and start fuzzing
      run: ./run.sh
